package RecnikPodatakaDSL.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class StructureReference_SubstituteMenu extends SubstituteMenuBase {
  public StructureReference_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for StructureReference. Generated from implicit smart reference attribute.", new SNodePointer("r:a35af346-76b2-4606-8b6b-acfcc9d832dc(RecnikPodatakaDSL.structure)", "865134009557824347")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_unqb9s_a(), CONCEPTS.StructureReference$NL));
    result.add(new SMP_Subconcepts_unqb9s_b());
    return result;
  }

  public class SMP_ReferenceScope_unqb9s_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_unqb9s_a() {
      super(CONCEPTS.StructureReference$NL, LINKS.structureRef$DKls, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_unqb9s_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_unqb9s_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "StructureReference", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.StructureReference$NL);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept StructureReference$NL = MetaAdapterFactory.getConcept(0x3978377fb27d4046L, 0x8bb64e4d30e8b603L, 0xc0192cc4acdb35bL, "RecnikPodatakaDSL.structure.StructureReference");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink structureRef$DKls = MetaAdapterFactory.getReferenceLink(0x3978377fb27d4046L, 0x8bb64e4d30e8b603L, 0xc0192cc4acdb35bL, 0xc0192cc4acdb35eL, "structureRef");
  }
}
